(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const STORAGE_KEY='sirilv.webide.workspace.v6',SESSION_KEY='sirilv.webide.session.v6',SETTINGS_KEY='sirilv.webide.settings.v6',COOKIE_KEY='sirilv_webide_v6';
const OLD_KEYS=['sirilv.webide.workspace.v4','sirilv.webide.session.v4','sirilv.webide.settings.v4'];
const TEXT_LIMIT=2*1024*1024,BINARY_LIMIT=8*1024*1024,HIGHLIGHT_LIMIT=220000;
const DEFAULT_SETTINGS={theme:'dark',accent:'#007acc',fontSize:14,lineHeight:155,tabSize:2,sidebarWidth:300,wordWrap:false,compact:false,autosave:true,syntax:true};
const state={workspace:null,currentPath:'/README.md',tabs:['/README.md'],dirty:new Set(),expanded:new Set(['/']),searchQuery:'',previewOpen:false,activePanel:'explorer',settings:structuredClone(DEFAULT_SETTINGS)};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function initialWorkspace(){return{type:'folder',name:'workspace',children:{'README.md':{type:'file',encoding:'text',content:`# SiriLV Web IDE

Это статическая Web IDE в стиле VSCodium. Она работает прямо в браузере и подходит для быстрых правок файлов на любом устройстве.

## Что умеет

- создавать файлы и папки;
- переименовывать, удалять и дублировать элементы;
- держать несколько файлов во вкладках;
- автоматически сохранять workspace в браузере;
- восстанавливать прошлую сессию через localStorage и cookie-метаданные;
- искать по файлам и содержимому;
- импортировать локальные текстовые и бинарные файлы;
- безопасно показывать preview для Markdown, HTML, SVG, JSON, изображений, audio/video, PDF и обычного текста;
- настраивать интерфейс: тема, accent color, размер шрифта, высота строк, tab size, ширина explorer, word wrap, compact UI, autosave;
- подсвечивать синтаксис для популярных текстовых форматов без тяжёлых библиотек.

## Горячие клавиши

- Ctrl/⌘ + S — сохранить;
- Ctrl/⌘ + N — создать файл;
- Ctrl/⌘ + Shift + P — command palette;
- Ctrl/⌘ + F — поиск;
- Ctrl/⌘ + B — sidebar;
- Ctrl/⌘ + W — закрыть вкладку;
- Escape — закрыть меню/палитру/sidebar.

## Важно

Код здесь не запускается. Это редактор файлов, а не полноценный удалённый контейнер. Для запуска, git commit/push и терминала нужен backend/OAuth или отдельная серверная часть.
`}}};}
function norm(p){const raw=String(p||'').trim().replaceAll('\\','/'),parts=[];for(const part of (raw.startsWith('/')?raw:'/'+raw).split('/')){if(!part||part=='.')continue;if(part=='..')parts.pop();else parts.push(part);}return'/'+parts.join('/');}
function base(p){return norm(p).split('/').filter(Boolean).pop()||'';}function dir(p){const a=norm(p).split('/').filter(Boolean);a.pop();return'/'+a.join('/');}
function node(p='/'){let n=state.workspace;for(const part of norm(p).split('/').filter(Boolean)){if(!n||n.type!='folder'||!n.children||!n.children[part])return null;n=n.children[part];}return n;}
function parent(p){const n=node(dir(p));return n&&n.type=='folder'?n:null;}
function entries(folder){return Object.entries(folder.children||{}).sort((a,b)=>a[1].type!=b[1].type?a[1].type=='folder'?-1:1:a[0].localeCompare(b[0],undefined,{numeric:true}));}
function allFiles(folder=state.workspace,prefix=''){let out=[];for(const[name,n]of entries(folder)){const p=prefix+'/'+name;if(n.type=='file')out.push(p);else out.push(...allFiles(n,p));}return out;}
function ensureFolder(p){let f=state.workspace;for(const part of norm(p).split('/').filter(Boolean)){if(!f.children[part])f.children[part]={type:'folder',children:{}};if(f.children[part].type!='folder')return null;f=f.children[part];}return f;}
function ext(p){const n=base(p),i=n.lastIndexOf('.');return i<0?'':n.slice(i+1).toLowerCase();}
function lang(p){return{js:'JavaScript',mjs:'JavaScript',cjs:'JavaScript',ts:'TypeScript',py:'Python',html:'HTML',htm:'HTML',css:'CSS',json:'JSON',md:'Markdown',txt:'Text',svg:'SVG',xml:'XML',sh:'Shell',bash:'Shell',yml:'YAML',yaml:'YAML',toml:'TOML',ini:'INI',png:'PNG image',jpg:'JPEG image',jpeg:'JPEG image',gif:'GIF image',webp:'WebP image',pdf:'PDF',mp3:'Audio',wav:'Audio',mp4:'Video',webm:'Video'}[ext(p)]||'Plain Text';}
function icon(p,n){if(n.type=='folder')return state.expanded.has(norm(p))?'▾':'▸';if(isBinary(n)){if(isImage(n))return'IMG';if((n.mime||'').startsWith('audio/'))return'AUD';if((n.mime||'').startsWith('video/'))return'VID';if(n.mime==='application/pdf')return'PDF';return'BIN';}return{js:'JS',ts:'TS',py:'PY',html:'<>',htm:'<>',css:'#',md:'MD',json:'{}',svg:'◇',txt:'TXT',sh:'$'}[ext(p)]||'•';}
function isBinary(n){return n?.encoding==='dataurl'||n?.binary===true;}function isImage(n){return isBinary(n)&&(n.mime||'').startsWith('image/');}
function setCookie(name,value,days=365){document.cookie=`${name}=${encodeURIComponent(value)}; Max-Age=${days*86400}; Path=/; SameSite=Lax`;}
function getCookie(name){const k=name+'=';for(const p of document.cookie.split(';')){const t=p.trim();if(t.startsWith(k))return decodeURIComponent(t.slice(k.length));}return'';}
function rgb(hex){const h=String(hex||'#007acc').replace('#',''),v=h.length==3?h.split('').map(x=>x+x).join(''):h,n=parseInt(v,16);return Number.isNaN(n)?'0,122,204':`${(n>>16)&255},${(n>>8)&255},${n&255}`;}
function restoreOld(k,old){return localStorage.getItem(k)||localStorage.getItem(old)||'';}
function persist(silent=false){const ws=JSON.stringify(state.workspace),session={currentPath:state.currentPath,tabs:state.tabs.filter(p=>node(p)?.type=='file'),expanded:Array.from(state.expanded),activePanel:state.activePanel,previewOpen:state.previewOpen,savedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,ws);localStorage.setItem(SESSION_KEY,JSON.stringify(session));localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings));setCookie(COOKIE_KEY,JSON.stringify({session,settings:state.settings,workspaceSmall:ws.length<2600?state.workspace:null}));state.dirty.clear();updateTabs();updateStatus();if(!silent)toast('Saved locally');}
function normalizeWorkspace(n){if(!n||typeof n!='object'||n.type!=='folder')return initialWorkspace();n.children=n.children&&typeof n.children=='object'?n.children:{};for(const [name,child]of Object.entries(n.children)){if(child?.type==='folder')normalizeWorkspace(child);else if(child?.type==='file'){if(child.encoding==='dataurl'||child.binary){child.encoding='dataurl';child.dataUrl=child.dataUrl||child.content||'';child.content='';child.mime=child.mime||'application/octet-stream';child.size=Number(child.size)||0;}else{child.encoding='text';child.content=String(child.content??'');}}else delete n.children[name];}return n;}
function load(){let c=null;try{c=JSON.parse(getCookie(COOKIE_KEY)||'null');}catch{}try{state.workspace=normalizeWorkspace(JSON.parse(restoreOld(STORAGE_KEY,OLD_KEYS[0])||'null')||c?.workspaceSmall||initialWorkspace());}catch{state.workspace=normalizeWorkspace(c?.workspaceSmall||initialWorkspace());}try{state.settings={...DEFAULT_SETTINGS,...(JSON.parse(restoreOld(SETTINGS_KEY,OLD_KEYS[2])||'null')||c?.settings||{})};}catch{state.settings={...DEFAULT_SETTINGS,...(c?.settings||{})};}let s=null;try{s=JSON.parse(restoreOld(SESSION_KEY,OLD_KEYS[1])||'null')||c?.session||null;}catch{s=c?.session||null;}const list=allFiles(),first=list[0]||'/README.md';state.currentPath=s?.currentPath&&node(s.currentPath)?.type=='file'?s.currentPath:first;state.tabs=Array.isArray(s?.tabs)?s.tabs.filter(p=>node(p)?.type=='file'):[state.currentPath];if(!state.tabs.length&&state.currentPath)state.tabs=[state.currentPath];if(state.currentPath&&!state.tabs.includes(state.currentPath))state.tabs.push(state.currentPath);state.expanded=new Set(Array.isArray(s?.expanded)?s.expanded:['/']);state.expanded.add('/');state.activePanel=s?.activePanel||'explorer';state.previewOpen=!!s?.previewOpen;}
function applySettings(){const r=document.documentElement,s=state.settings;r.dataset.theme=s.theme;r.dataset.wrap=String(s.wordWrap);r.dataset.compact=String(s.compact);r.style.setProperty('--accent',s.accent);r.style.setProperty('--accent-rgb',rgb(s.accent));r.style.setProperty('--font-size',s.fontSize+'px');r.style.setProperty('--line-height',String(s.lineHeight/100));r.style.setProperty('--tab-size',String(s.tabSize));r.style.setProperty('--sidebar-width',s.sidebarWidth+'px');const set=(id,v,prop='value')=>{const e=$(id);if(e)e[prop]=v;};set('#setTheme',s.theme);set('#setAccent',s.accent);set('#setFontSize',s.fontSize);set('#setLineHeight',s.lineHeight);set('#setTabSize',s.tabSize);set('#setSidebarWidth',s.sidebarWidth);set('#setWordWrap',s.wordWrap,'checked');set('#setCompact',s.compact,'checked');set('#setAutosave',s.autosave,'checked');}
function setupEditorDom(){const wrap=$('#editorWrap'),ed=$('#editor');if(!wrap||!ed)return;if(!$('#editorCell')){const cell=document.createElement('div');cell.id='editorCell';cell.className='editor-cell';const high=document.createElement('pre');high.id='highlightLayer';high.className='highlight-layer';high.innerHTML='<code></code>';wrap.append(cell);cell.append(high);cell.append(ed);}if(!$('#binaryView')){const view=document.createElement('section');view.id='binaryView';view.className='binary-view';view.hidden=true;$('.editor-area').append(view);}}
function render(){applySettings();renderPanels();renderTree();updateTabs();updateEditor();updateSearch();updatePreview();updateStatus();}
function renderPanels(){$$('[data-panel-view]').forEach(p=>p.hidden=p.dataset.panelView!==state.activePanel);$$('.activity').forEach(b=>b.classList.toggle('active',b.dataset.panel===state.activePanel));}
function renderTree(){const root=$('#fileTree');if(!root)return;root.innerHTML='';const box=document.createElement('div');box.className='tree-root';box.append(...renderFolder(state.workspace,''));root.append(box);$('#workspaceName').textContent=state.workspace.name||'workspace';}
function renderFolder(folder,prefix){return entries(folder).map(([name,child])=>{const p=norm(prefix+'/'+name),w=document.createElement('div');w.className='tree-node';if(child.type=='folder'&&!state.expanded.has(p))w.classList.add('collapsed');const row=document.createElement('button');row.type='button';row.className='tree-row'+(p===state.currentPath?' active':'');row.innerHTML=`<span class="tree-icon">${esc(icon(p,child))}</span><span class="tree-name">${esc(name)}</span>`;row.onclick=()=>child.type=='folder'?toggleFolder(p):openFile(p);row.oncontextmenu=e=>{e.preventDefault();context(e.clientX,e.clientY,p,child.type);};w.append(row);if(child.type=='folder'){const children=document.createElement('div');children.className='tree-children';children.append(...renderFolder(child,p));w.append(children);}return w;});}
function toggleFolder(p){state.expanded.has(p)?state.expanded.delete(p):state.expanded.add(p);renderTree();persist(true);}
function updateTabs(){const tabs=$('#tabs');if(!tabs)return;tabs.innerHTML='';for(const p of state.tabs.filter(p=>node(p)?.type=='file')){const b=document.createElement('button');b.type='button';b.className='tab'+(p===state.currentPath?' active':'')+(state.dirty.has(p)?' dirty':'');b.title=p;b.innerHTML=`<span>${esc(base(p))}</span><i>×</i>`;b.onclick=e=>e.target.tagName=='I'?closeTab(p):openFile(p);tabs.append(b);} }
function updateEditor(){const ed=$('#editor'),wrap=$('#editorWrap'),empty=$('#emptyState'),bin=$('#binaryView'),n=node(state.currentPath);const openTabs=state.tabs.filter(p=>node(p)?.type==='file');if(!openTabs.length){wrap.hidden=true;bin.hidden=true;empty.hidden=false;ed.value='';lineNumbers();return;}if(!n||n.type!=='file'){state.currentPath=openTabs.at(-1);return updateEditor();}empty.hidden=true;if(isBinary(n)){wrap.hidden=true;bin.hidden=false;renderBinaryView(n,state.currentPath);ed.value='';lineNumbers();return;}bin.hidden=true;wrap.hidden=false;if(ed.value!==n.content)ed.value=n.content;lineNumbers();highlight();}
function renderBinaryView(n,p){const box=$('#binaryView'),mime=n.mime||'application/octet-stream',size=formatBytes(n.size||0);let body='';if(mime.startsWith('image/'))body=`<img class="binary-image" src="${n.dataUrl}" alt="${esc(base(p))}">`;else if(mime.startsWith('audio/'))body=`<audio controls src="${n.dataUrl}"></audio>`;else if(mime.startsWith('video/'))body=`<video controls src="${n.dataUrl}"></video>`;else if(mime==='application/pdf')body=`<iframe class="binary-frame" src="${n.dataUrl}" title="${esc(base(p))}"></iframe>`;else body='<div class="binary-placeholder">Binary preview is not available for this type.</div>';box.innerHTML=`<div class="binary-card"><h2>${esc(base(p))}</h2><p>${esc(mime)} · ${size}</p><div class="binary-actions"><button id="downloadBinary" type="button">Download</button></div>${body}</div>`;$('#downloadBinary').onclick=()=>downloadPath(p);}
function formatBytes(n){if(!n)return'0 B';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++;}return`${n.toFixed(i?1:0)} ${u[i]}`;}
function lineNumbers(){const ed=$('#editor'),ln=$('#lineNumbers'),count=Math.max(1,ed.value.split('\n').length);ln.textContent=Array.from({length:count},(_,i)=>i+1).join('\n');ln.scrollTop=ed.scrollTop;const h=$('#highlightLayer');if(h){h.scrollTop=ed.scrollTop;h.scrollLeft=ed.scrollLeft;}}
function updateStatus(){const n=node(state.currentPath),content=n?.type==='file'&&!isBinary(n)?n.content:'',ed=$('#editor'),before=ed.value.slice(0,ed.selectionStart||0).split('\n'),row=before.length,col=before.at(-1).length+1;$('#statusPath').textContent=state.currentPath||'no file';$('#statusLang').textContent=n?.type==='file'?(isBinary(n)?(n.mime||'Binary'):lang(state.currentPath)):'No file';$('#statusStats').textContent=isBinary(n)?formatBytes(n.size||0):`${row}:${col} · ${content.length} chars`;$('#statusStorage').textContent=localStorage.getItem(STORAGE_KEY)?'localStorage + cookie':'cookie-ready';$('#statusSaved').textContent=state.dirty.size?'unsaved':'saved';}
function highlight(){const cell=$('#editorCell'),layer=$('#highlightLayer code'),ed=$('#editor'),n=node(state.currentPath);if(!cell||!layer||!n||isBinary(n))return;const text=n.content||'',enabled=state.settings.syntax!==false&&text.length<=HIGHLIGHT_LIMIT;cell.classList.toggle('no-highlight',!enabled);if(!enabled){layer.textContent='';return;}layer.innerHTML=syntax(text,ext(state.currentPath));$('#highlightLayer').scrollTop=ed.scrollTop;$('#highlightLayer').scrollLeft=ed.scrollLeft;}
function syntax(text,e){if(['js','mjs','cjs','ts'].includes(e))return codeSyntax(text,/(\/\/.*|\/\*[\s\S]*?\*\/|`(?:\\.|[^`])*`|"(?:\\.|[^"])*"|'(?:\\.|[^'])*'|\b(?:const|let|var|function|return|class|new|if|else|for|while|switch|case|break|continue|try|catch|finally|throw|async|await|import|export|from|default|extends|super|this|typeof|instanceof|in|of|true|false|null|undefined)\b|\b\d+(?:\.\d+)?\b)/g);if(e==='py')return codeSyntax(text,/(#.*|"""[\s\S]*?"""|'''[\s\S]*?'''|"(?:\\.|[^"])*"|'(?:\\.|[^'])*'|\b(?:def|class|return|if|elif|else|for|while|try|except|finally|with|as|import|from|pass|break|continue|lambda|yield|async|await|True|False|None|self|in|is|and|or|not)\b|\b\d+(?:\.\d+)?\b)/g);if(e==='json')return esc(text).replace(/("(?:\\.|[^"])*")(?=\s*:)/g,'<span class="tok-key">$1</span>').replace(/(:\s*)("(?:\\.|[^"])*"|true|false|null|-?\d+(?:\.\d+)?)/g,(m,a,b)=>a+`<span class="${b[0]=='&'||b[0]=='"'?'tok-str':'tok-num'}">${b}</span>`);if(['html','htm','xml','svg'].includes(e))return esc(text).replace(/(&lt;!--[\s\S]*?--&gt;)/g,'<span class="tok-com">$1</span>').replace(/(&lt;\/?[\w:-]+)([\s\S]*?)(&gt;)/g,(m,a,b,c)=>`<span class="tok-kw">${a}</span>${b.replace(/([\w:-]+)=(&quot;.*?&quot;|&#39;.*?&#39;)/g,'<span class="tok-key">$1</span>=<span class="tok-str">$2</span>')}<span class="tok-kw">${c}</span>`);if(e==='css')return esc(text).replace(/(\/\*[\s\S]*?\*\/)/g,'<span class="tok-com">$1</span>').replace(/([.#]?[\w-]+)(\s*\{)/g,'<span class="tok-kw">$1</span>$2').replace(/([\w-]+)(\s*:)/g,'<span class="tok-key">$1</span>$2').replace(/(".*?"|'.*?')/g,'<span class="tok-str">$1</span>');if(['sh','bash'].includes(e))return codeSyntax(text,/(#.*|"(?:\\.|[^"])*"|'(?:\\.|[^'])*'|\b(?:if|then|else|fi|for|while|do|done|case|esac|function|export|local|echo|exit|cd|mkdir|rm|cp|mv|grep|sed|awk)\b|\b\d+\b)/g);return esc(text);}
function codeSyntax(text,re){let out='',last=0;for(const m of text.matchAll(re)){out+=esc(text.slice(last,m.index));const raw=m[0],safe=esc(raw);let cls='tok-num';if(raw.startsWith('//')||raw.startsWith('/*')||raw.startsWith('#'))cls='tok-com';else if(raw[0]==='"'||raw[0]==="'"||raw[0]==='`')cls='tok-str';else if(/^[A-Za-z_$]/.test(raw))cls='tok-kw';out+=`<span class="${cls}">${safe}</span>`;last=m.index+raw.length;}return out+esc(text.slice(last));}
function updateSearch(){const box=$('#searchResults'),q=state.searchQuery.trim().toLowerCase();if(!box)return;box.innerHTML='';if(!q){box.innerHTML='<div class="empty">Type to search files and content.</div>';return;}const found=[];for(const p of allFiles()){const n=node(p);if(!n||isBinary(n)){if(p.toLowerCase().includes(q))found.push({p,line:0,text:n?.mime||'binary file'});continue;}const content=n.content||'',nameHit=p.toLowerCase().includes(q);content.split('\n').forEach((line,i)=>{if(nameHit||line.toLowerCase().includes(q))found.push({p,line:i+1,text:line.trim()||'empty line'});});}if(!found.length){box.innerHTML='<div class="empty">No results.</div>';return;}for(const m of found.slice(0,100)){const b=document.createElement('button');b.type='button';b.className='search-item';b.innerHTML=`<b>${esc(m.p)}${m.line?':'+m.line:''}</b><span>${esc(m.text)}</span>`;b.onclick=()=>openFile(m.p);box.append(b);}}
function updatePreview(){const panel=$('#previewPanel');if(!state.previewOpen){panel.hidden=true;return;}panel.hidden=false;const n=node(state.currentPath),content=n?.type==='file'&&!isBinary(n)?n.content:'',type=ext(state.currentPath),body=$('#previewBody');$('#previewTitle').textContent='Preview: '+(base(state.currentPath)||'empty');if(isBinary(n)){if(isImage(n))body.innerHTML=`<img class="binary-image" src="${n.dataUrl}" alt="${esc(base(state.currentPath))}">`;else if((n.mime||'').startsWith('audio/'))body.innerHTML=`<audio controls src="${n.dataUrl}"></audio>`;else if((n.mime||'').startsWith('video/'))body.innerHTML=`<video controls src="${n.dataUrl}"></video>`;else if(n.mime==='application/pdf')body.innerHTML=`<iframe class="binary-frame" src="${n.dataUrl}" title="${esc(base(state.currentPath))}"></iframe>`;else body.innerHTML=`<pre>${esc(n.mime||'Binary file')} · ${formatBytes(n.size||0)}</pre>`;return;}if(type==='html'||type==='htm'){body.innerHTML='<iframe title="HTML preview" sandbox=""></iframe>';$('iframe',body).srcdoc=content;}else if(type==='md')body.innerHTML=`<article class="markdown-preview">${markdown(content)}</article>`;else if(type==='svg')body.innerHTML=`<div class="svg-preview">${content}</div><pre>${esc(content)}</pre>`;else if(type==='json'){try{body.innerHTML='<pre>'+esc(JSON.stringify(JSON.parse(content),null,2))+'</pre>';}catch{body.innerHTML='<pre>'+esc(content)+'</pre>';}}else body.innerHTML='<pre>'+esc(content)+'</pre>';}
function markdown(src){return esc(src).replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/^[-*] (.*)$/gm,'<li>$1</li>').replace(/\n/g,'<br>');}
function openFile(p){p=norm(p);if(node(p)?.type!=='file')return toast('File not found',true);state.currentPath=p;if(!state.tabs.includes(p))state.tabs.push(p);document.body.classList.remove('show-sidebar');render();if(!isBinary(node(p)))$('#editor').focus();persist(true);}
function closeTab(p){state.tabs=state.tabs.filter(x=>x!==p);if(state.currentPath===p)state.currentPath=state.tabs.at(-1)||'';render();persist(true);}
function createFile(baseDir=dir(state.currentPath)||'/'){const target=prompt('File path:',norm(baseDir+'/untitled.txt'));if(!target)return;const p=norm(target),folder=ensureFolder(dir(p)),name=base(p);if(!name||!folder)return toast('Bad path',true);if(folder.children[name]&&!confirm('File exists. Replace it?'))return;folder.children[name]={type:'file',encoding:'text',content:''};state.expanded.add(dir(p));openFile(p);markDirty(p);}
function createFolder(baseDir=dir(state.currentPath)||'/'){const target=prompt('Folder path:',norm(baseDir+'/folder'));if(!target)return;const p=norm(target),folder=ensureFolder(dir(p)),name=base(p);if(!name||!folder)return toast('Bad path',true);if(folder.children[name])return toast('Item already exists',true);folder.children[name]={type:'folder',children:{}};state.expanded.add(dir(p));state.expanded.add(p);markDirty();render();}
function removePath(p){if(p==='/'||!p||!confirm('Delete '+p+'?'))return;const f=parent(p),name=base(p);if(!f?.children[name])return toast('Item not found',true);delete f.children[name];state.tabs=state.tabs.filter(t=>t!==p&&!t.startsWith(p+'/'));if(state.currentPath===p||state.currentPath.startsWith(p+'/'))state.currentPath=state.tabs.at(-1)||'';markDirty();render();}
function renamePath(p){const n=node(p),target=prompt('New path:',p);if(!n||!target)return;const next=norm(target),old=parent(p),fresh=ensureFolder(dir(next)),name=base(next);if(!old||!fresh||!name)return toast('Invalid path',true);if(fresh.children[name]&&next!==p&&!confirm('Target exists. Replace it?'))return;fresh.children[name]=structuredClone(n);delete old.children[base(p)];state.tabs=state.tabs.map(t=>t===p?next:t.startsWith(p+'/')?next+t.slice(p.length):t);if(state.currentPath===p||state.currentPath.startsWith(p+'/'))state.currentPath=next+state.currentPath.slice(p.length);markDirty(next);render();}
function duplicatePath(p){const n=node(p),f=parent(p);if(!n||!f)return toast('Item not found',true);const name=base(p),i=name.lastIndexOf('.'),stem=i<0?name:name.slice(0,i),suffix=i<0?'':name.slice(i);let copy=`${stem}_copy${suffix}`,num=2;while(f.children[copy])copy=`${stem}_copy_${num++}${suffix}`;f.children[copy]=structuredClone(n);markDirty(dir(p)+'/'+copy);render();}
function markDirty(p=state.currentPath){if(p)state.dirty.add(p);updateTabs();updateStatus();if(state.settings.autosave)scheduleSave();}
let saveTimer=null;function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist(true),450);}
function context(x,y,p,type){const menu=$('#contextMenu'),folder=type==='folder'?p:dir(p),items=[['Open',()=>type==='file'?openFile(p):toggleFolder(p)],['New file here',()=>createFile(folder)],['New folder here',()=>createFolder(folder)],['Rename',()=>renamePath(p)],['Duplicate',()=>duplicatePath(p)],['Delete',()=>removePath(p)]];if(type==='file')items.push(['Download',()=>downloadPath(p)]);menu.innerHTML='';for(const[label,fn]of items){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{menu.hidden=true;fn();};menu.append(b);}menu.style.left=Math.min(x,innerWidth-196)+'px';menu.style.top=Math.min(y,innerHeight-260)+'px';menu.hidden=false;}
function downloadBlob(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);}
async function dataUrlToBlob(dataUrl){const r=await fetch(dataUrl);return r.blob();}
async function downloadPath(p=state.currentPath){const n=node(p);if(n?.type!=='file')return toast('No file selected',true);if(isBinary(n))return downloadBlob(base(p),await dataUrlToBlob(n.dataUrl));downloadBlob(base(p),new Blob([n.content],{type:'text/plain;charset=utf-8'}));}
function exportWorkspace(){downloadBlob((state.workspace.name||'workspace')+'.json',new Blob([JSON.stringify(state.workspace,null,2)],{type:'application/json;charset=utf-8'}));toast('Workspace exported');}
function isTextFile(file){if(file.type.startsWith('text/'))return true;return /\.(txt|md|js|mjs|cjs|ts|py|html?|css|json|svg|xml|sh|bash|yml|yaml|toml|ini|csv|log)$/i.test(file.name);}
function readFile(file,mode){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(r.error);r.onload=()=>resolve(r.result);mode==='dataurl'?r.readAsDataURL(file):r.readAsText(file);});}
async function importFiles(fileList){const list=Array.from(fileList||[]);if(!list.length)return;for(const file of list){const p=norm('/imported/'+(file.webkitRelativePath||file.name)),folder=ensureFolder(dir(p));state.expanded.add('/imported');state.expanded.add(dir(p));if(file.size>BINARY_LIMIT){toast(`${file.name}: file is too large for browser storage`,true);continue;}if(file.name.endsWith('.json')){try{const text=await readFile(file,'text'),json=JSON.parse(text);if(json?.type==='folder'&&json.children&&confirm('Import '+file.name+' as full workspace?')){state.workspace=normalizeWorkspace(json);state.currentPath=allFiles()[0]||'/README.md';state.tabs=state.currentPath?[state.currentPath]:[];state.expanded=new Set(['/']);markDirty();render();persist();continue;}folder.children[base(p)]={type:'file',encoding:'text',content:text};continue;}catch{}}
if(isTextFile(file)&&file.size<=TEXT_LIMIT){folder.children[base(p)]={type:'file',encoding:'text',content:await readFile(file,'text'),mime:file.type||'text/plain',size:file.size};}else{folder.children[base(p)]={type:'file',encoding:'dataurl',binary:true,dataUrl:await readFile(file,'dataurl'),mime:file.type||'application/octet-stream',size:file.size,content:''};}}
markDirty('/imported');render();persist();toast('Files imported');}
function palette(){const m=$('#commandModal');m.hidden=false;$('#commandInput').value='';commandsRender('');$('#commandInput').focus();}
const commands=[['File: New File',()=>createFile()],['File: New Folder',()=>createFolder()],['File: Save Workspace',()=>persist()],['File: Download Current File',()=>downloadPath()],['Workspace: Export JSON',()=>exportWorkspace()],['Workspace: Import Files',()=>$('#fileInput').click()],['Workspace: Reset to README Only',()=>resetWorkspace()],['View: Toggle Sidebar',()=>document.body.classList.toggle('show-sidebar')],['View: Toggle Preview',()=>{state.previewOpen=!state.previewOpen;render();persist(true);}],['View: Toggle Theme',()=>toggleTheme()],['View: Open Settings',()=>setPanel('settings')],['Search: Focus Search',()=>{setPanel('search');$('#searchInput').focus();}]];
function commandsRender(q){const list=$('#commandList'),needle=q.trim().toLowerCase();list.innerHTML='';const filtered=commands.filter(([name])=>name.toLowerCase().includes(needle));if(!filtered.length){list.innerHTML='<div class="empty">No commands.</div>';return;}for(const[name,fn]of filtered){const b=document.createElement('button');b.type='button';b.textContent=name;b.onclick=()=>{$('#commandModal').hidden=true;fn();};list.append(b);}}
function setPanel(panel){state.activePanel=panel;renderPanels();document.body.classList.add('show-sidebar');persist(true);}
function toggleTheme(){state.settings.theme=state.settings.theme==='dark'?'light':state.settings.theme==='light'?'contrast':'dark';applySettings();persist(true);}
function resetSettings(){if(!confirm('Reset interface settings?'))return;state.settings=structuredClone(DEFAULT_SETTINGS);applySettings();persist();}
function resetWorkspace(){if(!confirm('Reset workspace to README.md only?'))return;state.workspace=initialWorkspace();state.currentPath='/README.md';state.tabs=['/README.md'];state.expanded=new Set(['/']);state.dirty.clear();render();persist();}
function toast(msg,error=false){const t=$('#toast');t.textContent=msg;t.className=error?'toast error show':'toast show';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1800);}
function bind(){const ed=$('#editor');ed.addEventListener('input',()=>{const n=node(state.currentPath);if(!n||n.type!=='file'||isBinary(n))return;n.content=ed.value;lineNumbers();highlight();updatePreview();markDirty(state.currentPath);});ed.addEventListener('scroll',lineNumbers);ed.addEventListener('keyup',updateStatus);ed.addEventListener('click',updateStatus);ed.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const start=ed.selectionStart,end=ed.selectionEnd,spaces=' '.repeat(Number(state.settings.tabSize)||2);ed.value=ed.value.slice(0,start)+spaces+ed.value.slice(end);ed.selectionStart=ed.selectionEnd=start+spaces.length;ed.dispatchEvent(new Event('input'));}});
$('#newFileTop').onclick=()=>createFile();$('#newFileSide').onclick=()=>createFile();$('#emptyNewFile').onclick=()=>createFile('/');$('#newFolderSide').onclick=()=>createFolder();$('#saveTop').onclick=()=>persist();$('#settingsTop').onclick=()=>setPanel('settings');$('#paletteTop').onclick=()=>palette();$('#importSide').onclick=()=>$('#fileInput').click();$('#exportSide').onclick=()=>exportWorkspace();$('#fileInput').onchange=e=>importFiles(e.target.files);$('#searchInput').oninput=e=>{state.searchQuery=e.target.value;updateSearch();};$('#closePreview').onclick=()=>{state.previewOpen=false;render();persist(true);};$('#closeCommands').onclick=()=>{$('#commandModal').hidden=true;};$('#commandInput').oninput=e=>commandsRender(e.target.value);$('#toggleSidebar').onclick=()=>document.body.classList.toggle('show-sidebar');$('#resetSettings').onclick=()=>resetSettings();$('#resetWorkspace').onclick=()=>resetWorkspace();
$$('.activity').forEach(b=>{b.onclick=()=>{if(b.dataset.panel)setPanel(b.dataset.panel);if(b.dataset.action==='preview'){state.previewOpen=!state.previewOpen;render();persist(true);}if(b.dataset.action==='theme')toggleTheme();};});
$('#setTheme').onchange=e=>{state.settings.theme=e.target.value;applySettings();persist(true);};$('#setAccent').oninput=e=>{state.settings.accent=e.target.value;applySettings();persist(true);};$('#setFontSize').oninput=e=>{state.settings.fontSize=Number(e.target.value);applySettings();lineNumbers();highlight();persist(true);};$('#setLineHeight').oninput=e=>{state.settings.lineHeight=Number(e.target.value);applySettings();lineNumbers();highlight();persist(true);};$('#setTabSize').onchange=e=>{state.settings.tabSize=Number(e.target.value);applySettings();persist(true);};$('#setSidebarWidth').oninput=e=>{state.settings.sidebarWidth=Number(e.target.value);applySettings();persist(true);};$('#setWordWrap').onchange=e=>{state.settings.wordWrap=e.target.checked;applySettings();persist(true);};$('#setCompact').onchange=e=>{state.settings.compact=e.target.checked;applySettings();persist(true);};$('#setAutosave').onchange=e=>{state.settings.autosave=e.target.checked;applySettings();persist(true);};
document.addEventListener('click',e=>{if(!e.target.closest('#contextMenu'))$('#contextMenu').hidden=true;});document.addEventListener('keydown',e=>{const k=e.key.toLowerCase(),mod=e.ctrlKey||e.metaKey;if(mod&&k==='s'){e.preventDefault();persist();}if(mod&&k==='n'){e.preventDefault();createFile();}if(mod&&e.shiftKey&&k==='p'){e.preventDefault();palette();}if(mod&&k==='f'){e.preventDefault();setPanel('search');$('#searchInput').focus();}if(mod&&k==='b'){e.preventDefault();document.body.classList.toggle('show-sidebar');}if(mod&&k==='w'){e.preventDefault();closeTab(state.currentPath);}if(e.key==='Escape'){$('#commandModal').hidden=true;$('#contextMenu').hidden=true;document.body.classList.remove('show-sidebar');}});window.addEventListener('beforeunload',()=>{if(state.dirty.size&&state.settings.autosave)persist(true);});}
load();document.addEventListener('DOMContentLoaded',()=>{setupEditorDom();bind();render();persist(true);toast('Workspace restored');});
})();
